//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Steel_Box.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SteelBoxDBEntitiy : DbContext
    {
        public SteelBoxDBEntitiy()
            : base("name=SteelBoxDBEntitiy")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coolers> Coolers { get; set; }
        public virtual DbSet<Frames> Frames { get; set; }
        public virtual DbSet<HardDrives> HardDrives { get; set; }
        public virtual DbSet<Motherboards> Motherboards { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStatuses> OrderStatuses { get; set; }
        public virtual DbSet<PCBuilds> PCBuilds { get; set; }
        public virtual DbSet<PowerUnits> PowerUnits { get; set; }
        public virtual DbSet<Processors> Processors { get; set; }
        public virtual DbSet<SolidStateDrivers> SolidStateDrivers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Videocards> Videocards { get; set; }
    }
}
